second increment
entertainment-veks/GoPracticum pull request #2
Opened 2021-09-02 20:29 UTC by entertainment-veks

2021-09-03 17:37 UTC, Barugoo commented on cmd/shortener/main.go
> +			w.WriteHeader(http.StatusBadRequest)
Давай вернем пользователю еще какое-нибудь поясняющее сообщение, что конкретно не так с его запросом. Рекомендую для этого воспользоваться функцией `http.Error`

2021-09-03 17:39 UTC, Barugoo commented on cmd/shortener/main.go
>  	router.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
А этот хэндлер обрабатывает GET или POST запрос? Похоже, что в твоей реализации - оба. В задании сказано, какая ручка какой http-метод должна обрабатывать, чекни еще раз

2021-09-03 17:40 UTC, Barugoo commented on cmd/shortener/main.go
>  	router.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
Давай вынесем объявление функций-обработчиков (`func(w http.ResponseWriter, r *http.Request)`) за пределы `SetupServer`, в виде отдельных именованых функций
Такой код будет гораздо проще поддерживать

2021-09-03 17:44 UTC, Barugoo commented on cmd/shortener/main.go
>  		link := string(body)
На 49 строке ты паникуешь при неудачной попытке вычитать тело запроса. Мы не используем панику при обработке таких ошибок, ее можно выбрасывать только в самых исключительных случаях. Здесь же я бы сделал:
```go
body, err := ioutil.ReadAll(temp) // по temp дальше коммент
if err != nil {
    http.Error(w, errors.New("unable to read request body"), http.StatusBadRequest)
}
```

2021-09-03 17:44 UTC, Barugoo commented on cmd/shortener/main.go
>  		link := string(body)
И еще: зачем нужна переменная temp? Тело запроса в данном случае просто указатель, ты не копируешь и не сохраняешь его содержимое присваивая значение переменной temp на 44 строке, а только сохраняешь адрес памяти, на который смотри интерфейс `io.ReadCloser`, коим является `r.Body`

2021-09-03 17:45 UTC, Barugoo commented on cmd/shortener/main.go
>  		var code = generateCode()
Лучше использовать короткую нотацию объявления с инициализацией:
`code := generateCode()`

2021-09-03 17:47 UTC, Barugoo commented on cmd/shortener/main.go
>  		w.Header().Set("Location", code)
А зачем здесь это? Заголовок `Location` мы используем обычно, чтобы указать на айдишнк или адрес только что созданного объекта на сервере

2021-09-03 17:49 UTC, Barugoo commented on cmd/shortener/main.go
>  	database := make(map[string]string)
Я бы вынес объявление хранилища из функции, которая возвращает тебе роутер. Это конечно компактно, тут спорить трудно, но например ты захочешь использовать другой роутер, или вообще вместо http-сервера принимать запросы по grpc -- тогда тебе придется дублировать код, а хотелось бы чтобы хранилище было отдельным модулем в программе, который можно переиспользовать.

2021-09-03 17:51 UTC, Barugoo requested changes
Указал на то, что хотелось бы улучшить в итоговой работе. Тесты проходят.
В целом ты молодец, очень жду доработанной домашки)

2021-09-14 19:14 UTC, Barugoo commented on cmd/shortener/main.go
> +	jsonResult, _ := json.Marshal(rawResult)
Стараемся никогда не заглушать ошибки
Если здесь мы не можем смаршалить структуру по какой-то причине (не важно насколько реален такой исход, ты никогда не знаешь наверняка где выстрелит ошибка) нужно обработать ошибку, залоггировав ее и вернув пользователю 500

2021-09-14 19:20 UTC, Barugoo commented on cmd/shortener/main.go
> +		"http://localhost:8080/" + code,
Зачастую сервер не знает по какому адресу до него можно достучаться, если мы ручками не прописали это в конфиге. Почему так происходит? Сервер может находится от клиента за завесой из прокси, веб-серверами типо nginx'a, защитами от дудоса типо клаудфлейр.  
Таким образом тот сервис, в котором ты обрабатываешь запрос, в реальных условиях может находиться очень далеко от того места, куда изначально свой запрос направил клиент, и может вообще ничего не знать о буквенном адресе, по которому изначально пользователь к нему обратился.

Поэтому этот адрес `http://localhost:8080/` должен быть конфигурируемый через например переменные окружения

2021-09-14 19:21 UTC, Barugoo commented on cmd/shortener/main.go
> +	jsonResult, _ := json.Marshal(rawResult)
Когда у тебя есть в распоряжении интерфейс `io.Writer` лучше использовать `json.NewEncoder(w).Encode(rawResult)` чтобы не хранить промежуточные данные в переменной (в данном случае jsonResult)

2021-09-14 19:22 UTC, Barugoo commented on cmd/shortener/main.go
> +		url string
Не забываем про json-тэги у полей структуры

2021-09-14 19:23 UTC, Barugoo approved these changes
Оставил еще мини комментарии, которые не указал на предыдущих ревью. Работу принимаю

2021-09-17 12:00 UTC, entertainment-veks commented on cmd/shortener/main.go
> +	jsonResult, _ := json.Marshal(rawResult)
`json.NewEncoder(w).Encode(rawResult)` - вау, это супер-метод! спасибо огромное!

2021-09-22 20:04 UTC, Barugoo commented on cmd/shortener/handler/get_handler.go
> +		}
Роутер gorilla/mux который ты используешь нужен в том числе для того, чтобы так не делать)
Ссылка на readme:
https://github.com/gorilla/mux/blob/master/doc.go#L83

2021-09-22 20:06 UTC, Barugoo commented on cmd/shortener/repository/repository.go
> +type Service struct {
Я бы перенес эту структуру из пакета Repository. 
Структура Service хранит какой-то общий стейт всей программы (судя по тому что тут есть BaseURL), что по смыслу несколько выходит за рамки пакета осуществляющего операции с хранилкой

2021-09-22 20:10 UTC, Barugoo commented on cmd/shortener/handler/get_handler.go
> +			http.Error(w, "Cannot find link", http.StatusInternalServerError)
Здесь `return`

2021-09-22 20:11 UTC, Barugoo commented on cmd/shortener/handler/get_handler.go
> +			http.Error(w, "Cannot find link", http.StatusInternalServerError)
А еще текст ошибки звучит так, будто записи с таким айдишником в базе нет, но на самом деле причиной может быть абсолютно все что угодно. Здесь ты никак не различаешь ошибки связанные с недоступностью базы и с отсутствием в базе искомой записи. Надо поправить

2021-09-22 20:13 UTC, Barugoo commented on cmd/shortener/handler/post_handler.go
> +	"GoPracticum/cmd/shortener/repository"
Названия модулей лучше все же начинать со строчной буквы и использовать snake_case

2021-09-22 20:13 UTC, Barugoo commented on cmd/shortener/handler/post_handler.go
> +	"GoPracticum/cmd/shortener/repository"
(просто вкусовщина)

2021-09-22 20:13 UTC, Barugoo commented on cmd/shortener/handler/post_handler.go
> +			http.Error(w, "Unable to read request body", http.StatusBadRequest)
Опять забыл `return`

2021-09-22 20:14 UTC, Barugoo commented on cmd/shortener/handler/post_json_handler.go
> +		json.Unmarshal(body, &link)
Давай здесь не будем игнорировать ошибку

2021-09-22 20:14 UTC, Barugoo commented on cmd/shortener/handler/post_json_handler.go
> +			http.Error(w, "Unable to read request body", http.StatusBadRequest)
return

2021-09-22 20:15 UTC, Barugoo commented on cmd/shortener/handler/post_json_handler.go
> +		json.NewEncoder(w).Encode(rawResult)
Здесь тоже не игнорим ошибку

2021-09-22 20:16 UTC, Barugoo commented on cmd/shortener/main.go
> +		os.Setenv("SERVER_ADDRESS", s)
Интересный rewrite конфигов. В продакшне такого не встречал никогда, но в чем причина сходу сказат не могу

2021-09-22 20:18 UTC, Barugoo commented on cmd/shortener/main.go
> +		os.Setenv("SERVER_ADDRESS", ":8080")
Если ты хочешь прописывать дефолтные значения, то лучше вынести конфиг в отдельную структуру и воспользоваться пакетом https://github.com/kelseyhightower/envconfig
В нем ты можешь тэгами полей прописывать дефолтные значения. Так они будут у тебя все в одном месте и не придется их отлавливать в os.Setenv'ах

2021-09-22 20:25 UTC, Barugoo commented on cmd/shortener/repository/repository.go
> +	}
Не слишком удобно то, что ты на каждый запрос делаешь открытие файла - это не дешевая операция, тк открытие файла инициирует системный вызов (syscall), а следовательно и переключение контекста OS. Иными словами, если мы будем открывать в каждом запросе файл под мьютексом, мы сильно просядем по скорости обработки запросов. 
Нужно сделать так, чтобы файл открывался и закрывался только один раз в течении жизни программы.

2021-09-22 20:27 UTC, Barugoo commented on cmd/shortener/repository/repository.go
> +		currentKey = decoded.Key
Эту операцию можно перенести в цикл `for` в третий блок

2021-09-22 20:28 UTC, Barugoo commented on cmd/shortener/repository/repository.go
> +	scanner := bufio.NewScanner(file)
Круто что ты задумался о построчном считывании файла, а не всего его целиком

2021-09-22 20:29 UTC, Barugoo requested changes
Хорошо, но надо переделать. Есть замечания по структуре, реализации хэндлеров и главным образом - открытие файла не должно происходить при каждом запросе, подробнее в комментах

Жду дороботок:)

2021-09-29 04:44 UTC, Barugoo approved these changes
Пятый тест не работает, работу принимаю

2021-09-30 15:19 UTC, merged